services:
  - type: web
    name: ai-docvault
    runtime: python
    region: oregon  # Choose "oregon" for free tier
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        value: "envVars:
  - key: DATABASE_URL
    value: "mysql+pymysql://root:root@localhost:3306/ai_docvault"

